### ISSUE TITLE
Unable to read gtf in scrinvex/src/scrinvex.cpp (Line 51)

### ISSUE THREAD

**Issue by Elhl93** [broadinstitute/scrinvex#1]
Hi, 
I am very interested in using your tool for our single-nuclei sequencing data. The following was done using your provided docker image (gcr.io/broad-cga-aarong-gtex/scrinvex). After executing: 

gtf=/path/to/file.gtf
bam=/path/to/bam.bam
[docker run gcr.io/broad-cga-aarong-gtex/scrinvex scrinvex $gtf $bam](url)

I get the error: 
`Unable to open GTF file: /path/to/file.gtf `

Note: The if condition in Line 51 of the C++ script returns False. 

The path to the gtf is correct, permission rights are also not the problem here. The collapse_annotation.py ran through with my Ensembl gtf without any problems and looks like. 

#!genome-build GRCh38.p5
#!genome-version GRCh38
#!genome-date 2013-12
#!genome-build-accession NCBI:GCA_000001405.20
#!genebuild-last-updated 2015-10
#!collapsed version generated by GTEx pipeline
1	havana	gene	29554	31109 [...]
[....]

Any ideas here?

**Comment by agraubert** [comment]
Docker containers run on a virtualized filesystem separate from your own. In this case, it is likely that `/path/to/file.gtf` is not accessible from inside the docker container. I would recommend using [docker run's `-v` option](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only) to expose part of your filesystem to the docker container.

Something like:
`docker run -v /path/to:/path/to gcr.io/broad-cga-aarong-gtex/scrinvex scrinvex $gtf $bam`
which would mount `/path/to` from your filesystem into the container at the same path so your shell variables would work fine

**Comment by Elhl93** [comment]
Problem solved, thanks a lot!
